### ISSUE TITLE
Plugwise Serial issue

### ISSUE THREAD

**Issue by pepijng** [SevenW/Plugwise-2-py#19]
I get the following error:
```
Traceback (most recent call last):
  File "./Plugwise-2.py", line 1352, in <module>
    main=PWControl()
  File "./Plugwise-2.py", line 125, in __init__
    self.device = Stick(port, timeout=1)
  File "/opt/plugwise/plugwise/api.py", line 57, in __init__
    SerialComChannel.__init__(self, port=port, timeout=timeout)
  File "/opt/plugwise/swutil/util.py", line 135, in __init__
    self.open()
  File "/opt/plugwise/swutil/util.py", line 144, in open
    self._fd = serial.Serial(port=self.port, baudrate=self.baud, bytesize=self.bits, parity=self.parity, stopbits=self.stop, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialutil.py", line 180, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 311, in open
    self._update_dtr_state()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 605, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
IOError: [Errno 22] Invalid argument
```
Any idea?

**Comment by SevenW** [comment]
I recently made some changes to handling serial ports, which might have caused this. I made code to recover from short moments of disconnected usbserial devices. Another cause might be that you are using a newer version of the pyserial library. Searching the web I find some similar complaints on pyserial in january this year.

Could you figure out the version of pyserial?
`pip show pyserial`

if it is version 3.0, you could try to uninstall pyserial first, and then reinstall an older version:
`sudo pip uninstall pyserial`
`sudo pip install pyserial==2.7`

Finally, I would expect that the issue is already solved by pyserial, so installing the latest version of pyserial might also help. So maybe trying first
`sudo pip install pyserial --upgrade`
solves the problem.

**Comment by pepijng** [comment]
pip show pyserial
```
---
Metadata-Version: 2.0
Name: pyserial
Version: 3.0.1
Summary: Python Serial Port Extension
Home-page: https://github.com/pyserial/pyserial
Author: Chris Liechti
Author-email: cliechti@gmx.net
License: Python
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

Downgrading to 2.7 did the trick, it works again. So it's not working with the latest pyserial

**Comment by SevenW** [comment]
It looks like a future release of pyserial, 3.1.0 contains a fix for 
this problem. So lets wait for this and see.

Good to hear that it works again.

SevenW

---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by SevenW** [comment]
No further information on this. Close.
