### ISSUE TITLE
Missing day log for device

### ISSUE THREAD

**Issue by heggink** [SevenW/Plugwise-2-py#32]
Hi SevenW,

I use your app for logging my plugin-hybrid car power consumption. I nicely get a consumption file for every day except for Jan-1st. Any thoughts on how to fix/reproduce?

Thx!

**Comment by SevenW** [comment]
Are we talking logging in the pwact or pwlog folders?
Can you check the folder for 2016? Maybe it is added there?

On my system all files are there. It can happen that a circle that is having a bad connection only logs a few days later to the pwlog folder, but with the right time labeling.

**Comment by heggink** [comment]
pwlog folder. There is a file in the pwact folder but not in the pwlog folder. I use that folder to summ consumption (awk '{s+=$3}END{print s/1000}' pw-2017-01-01-XXXXXXXX.log). Not sure what the format of the pwact folder is.

**Comment by SevenW** [comment]
OK, the missing file is in the pwlog folder. That means logging form the history buffers in the circles themselves. This should actually always be added, also if the circle have been offline for a while.
So to me this is a complete mystery. Currently I do not have enough information to start looking for a defect.

I could give you instructions to re-capture all content of the historic buffers I you like. If the error then reproduces I can start deeper investigations.

**Comment by heggink** [comment]
Instructions would be most welcome. Thx!

**Comment by etennapel** [comment]
Could this problem also relate to the fact that the **yrfolder** variable in the main file is not re-initialized when entering a new year? In that case, it seems that the logfilenames still use the previous year. It is only set only when starting the script.

My proposal would be to re-initialize the variable, and thus filenames?

**Comment by SevenW** [comment]
@etennapel: Thanks for looking into the issue. It is not the root cause, as the creation of folders in a new year happens here 
https://github.com/SevenW/Plugwise-2-py/blob/master/Plugwise-2.py#L624
and here:
https://github.com/SevenW/Plugwise-2-py/blob/master/Plugwise-2.py#L1045

**Comment by SevenW** [comment]
@heggink: It is actually very simple to start retrieving all of the circles historic buffers again. That is the by default hourly logging stored in the pwlog folders. You may be retrieving both the pwlog type and the 10-seconds pwact readings. It is best to make a backup copy of your complete pwlog folder because rereading pwlog will append to existing files of the same day. After rereading the pwlog, you may manually want to merge again your backup folder with the new folder. Take care with merging into one folder structure again. It is easy enough to loose data. pwact data can never be reretrieved. So in the merge step, todays file needs to be manually concatenated if you want to have it as complete as possible. The steps:

 1. stop Plugwwise-2.py
from your home folder
2. mv pwlog pwlog-bck
3. restart Plugwise-2.py
4. Let it run for several hours because it starts rereading all the stored information in the circles.

Simple.

What is behind this:
The key element is removing the pwlastlog.log file from pwlog folder. If that is not present, it starts reading the historic buffers form the start. You could also only remove the particular line for the specific circle form that file. However, only removing the file will result in appending some loggin for a second time to exisitng files. Therefore, try the simple approach.

Please let me know if the problem now persists.
